name: flutter_tab
description: A new Flutter package.
version: 0.0.1
author: wapchief <wapchief@gmail.com>
homepage: https://github.com/wapchief/flutter-tab-layout

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
